server:
  port: 8300
spring:
  http:
    multipart:
      max-file-size: 10M
  application:
    name: dianhu
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dianhu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 122654
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 300
    pool:
      max-wait: -1
      max-idle: 5
      min-idle: 0
      max-active: 20
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hltx.usermanage.beans
rocketmq:
  producer:
    group: producer_bank2
  name-server: 127.0.0.1:9876
upload:
  imgpath: F:/img/upload/img/
  imgmaxsize: 10485760
  videopath: F:/img/upload/video/
  videomaxsize: 104857600
  qrcode: F:/img/upload/qrcode/
logging:
  level:
    com.hltx.dianhu.mapper: debug